version: "3.7"

services:
  database_rentcar:
    image: postgres
    container_name: database_rentcar
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=apinodejsrentcar
      - POSTGRES_DB=rentcar
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentcar-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_rentcar
    depends_on:
      - database_rentcar

volumes:
  pgdata:
    driver: local
